# Generated by Django 3.0.5 on 2020-04-27 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ring',
            name='how_to_get',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ring',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='ring',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rings.Location'),
        ),
        migrations.AlterField(
            model_name='ring',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
